### PR TITLE
test on wordpress 5.8

### PR DESCRIPTION
**Pull request by oshi97**
Created a new wordpress site, added the plugin, put in all required config.
See the searchbar page redirect correctly to the results page, with everything
displaying as expected. The active wordpress theme can affect the styling of
the redirect searchbar which I believe makes sense.

Tested changing the placeholder text.

J=SLAP-1443
TEST=manual

### CODE REVIEW

**Comment by cea2aj** [comment]
We also want to update these files within the zip file, right?

**Comment by cea2aj** [comment]
Unrelated, but on the README it says that downloading the zip is necessary when installing the plugin from within Wordpress. Is that wrong? I would think that you would only need to download the zip fo manual installations

**Comment by oshi97** [comment]
> Unrelated, but on the README it says that downloading the zip is necessary when installing the plugin from within Wordpress. Is that wrong? I would think that you would only need to download the zip fo manual installations

I think you're right! I'll ask @rosiegrant

**Review by cea2aj — APPROVED** [review]
Looks good!

Maybe in the future we can make a script for generating the zip

**Review by cea2aj — APPROVED** [review]

**Pull request merged**
